import Link from "next/link";
import PageHero from "./PageHero";
import { devotionalBase, devotionalJsonLd } from "@/lib/devotional";

export default function ZiyaratPage({ entry }) {
  const url = `${devotionalBase}${entry.path}`;
  const schema = [
    { "@context": "https://schema.org", "@type": "WebPage", "@id": `${url}#webpage`, url, name: entry.title, alternateName: entry.urduTitle, description: entry.description, inLanguage: ["en", "ar", "ur"], isPartOf: { "@type": "CollectionPage", name: "Shia Ziyarat Library", url: `${devotionalBase}/ziyarat` }, citation: entry.sources.map((source) => source.url) },
    { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: devotionalBase }, { "@type": "ListItem", position: 2, name: "Ziyarats", item: `${devotionalBase}/ziyarat` }, { "@type": "ListItem", position: 3, name: entry.title, item: url }] },
  ];
  const hasTransliteration = entry.blocks.some((block) => block.transliteration);
  const hasEnglish = entry.blocks.some((block) => block.english);
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: devotionalJsonLd(schema) }} />
    <PageHero eyebrow={`Ziyarats · ${entry.group}`} title={entry.title} lead={entry.intro} />
    <section className="bg-coal py-12 sm:py-16"><article className="mx-auto max-w-4xl px-4 sm:px-6">
      <nav aria-label="Breadcrumb" className="mb-8 flex flex-wrap items-center gap-2 text-sm text-sand"><Link href="/" className="hover:text-goldbright">Home</Link><span aria-hidden="true">/</span><Link href="/ziyarat" className="text-goldbright">Ziyarats</Link><span aria-hidden="true">/</span><span>{entry.title}</span></nav>
      <p lang="ur" dir="rtl" className="mb-8 font-arabic text-3xl leading-loose text-goldbright">{entry.urduTitle}</p>
      <div className="card-gold mb-8 rounded-2xl p-6"><h2 className="font-display text-xl text-goldbright">Recitation & Edition</h2><p className="mt-3 leading-relaxed text-sand">{entry.intro}</p>{entry.edition && <p className="mt-3 text-sm leading-relaxed text-sand">{entry.edition}</p>}<p className="mt-3 text-sm leading-relaxed text-sand">{entry.scanned ? "This edition is presented as complete Arabic and Urdu source scans. A typed transcription, Roman transliteration and English translation of these scans have not yet been added." : entry.hasUrduTranslation ? "This page includes Arabic text, English meaning and a complete Urdu meaning for the selected edition. Available Roman transliteration appears alongside the Arabic." : "This page includes Arabic text and English meaning, with available Roman transliteration. A complete Urdu translation of this edition has not yet been added; the Urdu guidance below is not a translation."}</p></div>
      <nav aria-label="Reading sections" className="mb-8 flex flex-wrap gap-3"><a href="#ziyarat-text" className="btn-outline-gold rounded-full px-5 py-2 text-sm">{entry.scanned ? "Arabic & Urdu scans" : "Arabic & English"}</a><a href="#urdu-reading" className="btn-outline-gold rounded-full px-5 py-2 text-sm">{entry.hasUrduTranslation ? "Urdu meaning" : "Urdu guidance"}</a><a href="#source-references" className="btn-outline-gold rounded-full px-5 py-2 text-sm">Sources</a></nav>
      <section id="ziyarat-text" aria-labelledby="reading-heading">
        <h2 id="reading-heading" className="mb-6 font-display text-2xl text-goldbright">{entry.scanned ? "Arabic & Urdu: Source Reading Edition" : hasTransliteration ? "Arabic Text, Transliteration & English Meaning" : "Arabic Text & English Meaning"}</h2>
        {entry.scanned ? <div className="space-y-6">{entry.images.map((img, index) => <figure key={img.url} className="card-gold rounded-2xl p-4 sm:p-6"><a href={img.url} aria-label={`Open source scan ${index + 1} at full size`}><img src={img.url} width={img.width} height={img.height} loading="lazy" alt={`${entry.title}: Arabic recitation and Urdu translation, source page ${index + 1}`} className="mx-auto h-auto max-w-full rounded-lg" /></a><figcaption className="mt-4 text-sm text-sand">Source scan {index + 1} of {entry.images.length} · Ziaraat.Com · select the image to read at full size.</figcaption></figure>)}</div> : <div className="space-y-6">{entry.blocks.map((block, index) => block.kind === "heading" ? <h3 key={index} className="pt-6 font-display text-xl text-goldbright">{block.text}</h3> : block.kind === "note" ? <p key={index} className="whitespace-pre-line border-l-2 border-gold/40 pl-4 text-sm leading-relaxed text-sand">{block.text}</p> : <section key={index} className="card-gold rounded-2xl p-5 sm:p-8" aria-label={`Recitation passage ${index + 1}`}><p className="mb-3 text-xs uppercase tracking-wide text-gold">Arabic · عربی</p><p lang="ar" dir="rtl" className="whitespace-pre-line break-words font-arabic text-3xl leading-[2.2] text-ivory sm:text-4xl">{block.arabic}</p>{block.transliteration && <><h3 className="mb-2 mt-7 text-sm font-semibold text-goldbright">Roman Transliteration</h3><p lang="en" className="whitespace-pre-line leading-loose text-sand">{block.transliteration}</p></>}{block.english && <><h3 className="mb-2 mt-6 text-sm font-semibold text-goldbright">English Meaning</h3><p lang="en" className="whitespace-pre-line leading-loose text-ivory">{block.english}</p></>}</section>)}</div>}
        {!entry.scanned && <p className="mt-5 text-sm leading-relaxed text-sand">{entry.translationNote}</p>}
      </section>
      <section id="urdu-reading" className="mt-12" aria-labelledby="urdu-heading"><h2 id="urdu-heading" className="mb-6 font-display text-2xl text-goldbright">{entry.hasUrduTranslation ? "Urdu Meaning · اردو ترجمہ" : "Urdu Reading Guidance · اردو رہنمائی"}</h2>{entry.hasUrduTranslation ? <div className="card-gold space-y-6 rounded-2xl p-5 sm:p-8">{entry.urdu.map((paragraph, index) => <p key={index} lang="ur" dir="rtl" className="whitespace-pre-line break-words font-arabic text-2xl leading-loose text-ivory">{paragraph}</p>)}</div> : <div className="card-gold rounded-2xl p-5 sm:p-8"><p lang="ur" dir="rtl" className="font-arabic text-2xl leading-loose text-ivory">{entry.urduGuidance}</p><p lang="ur" dir="rtl" className="mt-5 font-arabic text-xl leading-loose text-sand">{entry.scanned ? "عربی متن اور اردو ترجمہ اوپر اصل صفحات کی تصاویر میں موجود ہے۔ تصویر منتخب کر کے بڑا صفحہ کھول سکتے ہیں۔" : "اس نسخے کا مکمل اردو ترجمہ ابھی شامل نہیں ہوا۔ یہ عبارت پڑھنے کی رہنمائی ہے، زیارت کا ترجمہ نہیں۔"}</p></div>}</section>
      <section id="source-references" className="mt-12 border-t border-gold/20 pt-8" aria-labelledby="sources-heading"><h2 id="sources-heading" className="font-display text-2xl text-goldbright">Sources & References</h2><p className="mt-3 text-sm leading-relaxed text-sand">Credit to Ziaraat.Com and the original recitation references below. Source collections may contain alternative versions and additional prayers; this page identifies the edition it presents.</p><ul className="mt-4 space-y-3">{entry.sources.map((source) => <li key={source.url}><a href={source.url} className="text-goldbright underline decoration-gold/40 underline-offset-4">{source.label}</a></li>)}</ul></section>
      <section className="mt-12" aria-labelledby="related-heading"><h2 id="related-heading" className="font-display text-2xl text-goldbright">Related Readings</h2><ul className="mt-5 space-y-4">{entry.related.map((item) => <li key={item.path}><Link href={item.path} className="text-goldbright underline decoration-gold/40 underline-offset-4">{item.title} →</Link></li>)}</ul></section>
      <Link href="/ziyarat" className="btn-outline-gold mt-10 inline-block rounded-full px-6 py-3 text-sm">Browse All Ziyarats →</Link>
    </article></section>
  </>;
}
